# Generated by Django 3.2.21 on 2023-10-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thief', '0003_alter_criminals_police'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar_person',
            name='F_lattitude',
        ),
        migrations.RemoveField(
            model_name='familiar_person',
            name='F_longitude',
        ),
    ]
