# Generated by Django 3.2.21 on 2023-10-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thief', '0004_auto_20231005_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_proof',
        ),
    ]
